service: HelloWorld-charter

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  region: us-east-2

functions:
##triggers index.js 'module.exports.handler'
#  app:
#    handler: index.handler
#    events:
#      - http:
#          path: any /
#          method: any
#          cors: true
#      - http: 'ANY {proxy+}'

#triggers handler.js 'module.exports.hello'
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get




