service: HelloWorld-charter

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  region: us-east-2

#triggers handler.js 'module.exports.hello'
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users
          method: get
          cors: true

#triggers index.js 'module.exports.handler'
  app:
    handler: index.handler
    events:
      - http:
          path: ANY /
          method: any
          cors: true


