service: HelloWorld-charter

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  region: us-east-2

functions:
#this triggers handler.js 'module.exports.hello'
#<cors: true> not needed if headers included in ajax call
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get

  customMessage:
    handler: customMessage.handler
    events:
      - cognitoUserPool:
          pool: demo
          trigger: CustomMessage


##triggers index.js 'module.exports.handler'
#Using handler.js becasue shortcut callback funct causes errors
#  app:
#    handler: index.handler
#    events:
#      - http:
#          path: any /
#          method: any
#          cors: true
#      - http: 'ANY {proxy+}'

#  preSignUp:
#    handler: preSignUp.handler
#    events:
#      - cognitoUserPool:
#          pool: demo
#          trigger: PreSignUp