service: HelloWorld-charter

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get